#ifndef UNIMPI_MT_CONSTANTS_H
#define UNIMPI_MT_CONSTANTS_H
#include <stdint.h>
#include "unimpi_version.h"

/* MPI-T tool-interface constants. Every MPI_T_* enumeration value and NULL
 * handle is backend-specific (e.g. MPI_T_BIND_NO_OBJECT is 0 on OpenMPI but
 * 9700 on the MPICH family), so none may be hardcoded: each is a
 * backend-filled extern, exposed internally under the UNIMPI_T_* names and
 * mapped to the standard MPI_T_* names by unimpi_std_macros.h. Filled by each
 * backend at init; a backend that does not export a value leaves it 0/NULL. */
#if UNIMPI_MPI_AT_LEAST(3,0)
/* MPI-T pvar classes */
extern int UNIMPI_T_PVAR_CLASS_STATE, UNIMPI_T_PVAR_CLASS_LEVEL,
    UNIMPI_T_PVAR_CLASS_SIZE, UNIMPI_T_PVAR_CLASS_PERCENTAGE,
    UNIMPI_T_PVAR_CLASS_HIGHWATERMARK, UNIMPI_T_PVAR_CLASS_LOWWATERMARK,
    UNIMPI_T_PVAR_CLASS_COUNTER, UNIMPI_T_PVAR_CLASS_AGGREGATE,
    UNIMPI_T_PVAR_CLASS_TIMER, UNIMPI_T_PVAR_CLASS_GENERIC,
    UNIMPI_T_PVAR_CLASS_INVALID;
/* MPI-T object bindings */
extern int UNIMPI_T_BIND_NO_OBJECT, UNIMPI_T_BIND_MPI_COMM,
    UNIMPI_T_BIND_MPI_DATATYPE, UNIMPI_T_BIND_MPI_ERRHANDLER,
    UNIMPI_T_BIND_MPI_FILE, UNIMPI_T_BIND_MPI_GROUP, UNIMPI_T_BIND_MPI_OP,
    UNIMPI_T_BIND_MPI_REQUEST, UNIMPI_T_BIND_MPI_WIN,
    UNIMPI_T_BIND_MPI_MESSAGE, UNIMPI_T_BIND_MPI_INFO,
    UNIMPI_T_BIND_MPI_SESSION, UNIMPI_T_BIND_INVALID;
/* MPI-T scopes */
extern int UNIMPI_T_SCOPE_CONSTANT, UNIMPI_T_SCOPE_READONLY,
    UNIMPI_T_SCOPE_LOCAL, UNIMPI_T_SCOPE_GROUP, UNIMPI_T_SCOPE_GROUP_EQ,
    UNIMPI_T_SCOPE_ALL, UNIMPI_T_SCOPE_ALL_EQ, UNIMPI_T_SCOPE_INVALID;
/* MPI-T sources */
extern int UNIMPI_T_SOURCE_ORDINARY, UNIMPI_T_SOURCE_DISTRIBUTED;
/* MPI-T verbosity levels */
extern int UNIMPI_T_VERBOSITY_USER_BASIC, UNIMPI_T_VERBOSITY_USER_DETAIL,
    UNIMPI_T_VERBOSITY_USER_ALL, UNIMPI_T_VERBOSITY_TUNER_BASIC,
    UNIMPI_T_VERBOSITY_TUNER_DETAIL, UNIMPI_T_VERBOSITY_TUNER_ALL,
    UNIMPI_T_VERBOSITY_MPIDEV_BASIC, UNIMPI_T_VERBOSITY_MPIDEV_DETAIL,
    UNIMPI_T_VERBOSITY_MPIDEV_ALL, UNIMPI_T_VERBOSITY_INVALID;
/* MPI-T NULL handles */
extern intptr_t UNIMPI_T_PVAR_HANDLE_NULL;
extern intptr_t UNIMPI_T_CVAR_HANDLE_NULL;
extern intptr_t UNIMPI_T_SESSION_NULL;
#endif /* UNIMPI_MPI_AT_LEAST(3,0) */
#endif /* UNIMPI_MT_CONSTANTS_H */
