#include "unimpi_mt_constants.h"
#include "unimpi_errors.h"
#if UNIMPI_MPI_AT_LEAST(3,0)
/* MPI-T tools-interface constants. All start at 0 (placeholder) and are
 * filled with the active backend's values at backend init. */

/* MPI_T_ERR_* error codes (declared extern in unimpi_errors.h) */
int MPI_T_ERR_MEMORY = 0;
int MPI_T_ERR_NOT_INITIALIZED = 0;
int MPI_T_ERR_CANNOT_INIT = 0;
int MPI_T_ERR_NOT_SUPPORTED = 0;
int MPI_T_ERR_INVALID_INDEX = 0;
int MPI_T_ERR_INVALID_ITEM = 0;
int MPI_T_ERR_INVALID_HANDLE = 0;
int MPI_T_ERR_OUT_OF_HANDLES = 0;
int MPI_T_ERR_OUT_OF_SESSIONS = 0;
int MPI_T_ERR_INVALID_SESSION = 0;
int MPI_T_ERR_CVAR_SET_NOT_NOW = 0;
int MPI_T_ERR_CVAR_SET_NEVER = 0;
int MPI_T_ERR_PVAR_NO_STARTSTOP = 0;
int MPI_T_ERR_PVAR_NO_WRITE = 0;
int MPI_T_ERR_PVAR_NO_ATOMIC = 0;
int MPI_T_ERR_INVALID = 0;
int MPI_T_ERR_INVALID_NAME = 0;
int MPI_T_ERR_INVALID_ENUM = 0;

/* UNIMPI_T_PVAR_CLASS_* */
int UNIMPI_T_PVAR_CLASS_STATE = 0;
int UNIMPI_T_PVAR_CLASS_LEVEL = 0;
int UNIMPI_T_PVAR_CLASS_SIZE = 0;
int UNIMPI_T_PVAR_CLASS_PERCENTAGE = 0;
int UNIMPI_T_PVAR_CLASS_HIGHWATERMARK = 0;
int UNIMPI_T_PVAR_CLASS_LOWWATERMARK = 0;
int UNIMPI_T_PVAR_CLASS_COUNTER = 0;
int UNIMPI_T_PVAR_CLASS_AGGREGATE = 0;
int UNIMPI_T_PVAR_CLASS_TIMER = 0;
int UNIMPI_T_PVAR_CLASS_GENERIC = 0;
int UNIMPI_T_PVAR_CLASS_INVALID = 0;

/* UNIMPI_T_BIND_* */
int UNIMPI_T_BIND_NO_OBJECT = 0;
int UNIMPI_T_BIND_MPI_COMM = 0;
int UNIMPI_T_BIND_MPI_DATATYPE = 0;
int UNIMPI_T_BIND_MPI_ERRHANDLER = 0;
int UNIMPI_T_BIND_MPI_FILE = 0;
int UNIMPI_T_BIND_MPI_GROUP = 0;
int UNIMPI_T_BIND_MPI_OP = 0;
int UNIMPI_T_BIND_MPI_REQUEST = 0;
int UNIMPI_T_BIND_MPI_WIN = 0;
int UNIMPI_T_BIND_MPI_MESSAGE = 0;
int UNIMPI_T_BIND_MPI_INFO = 0;
int UNIMPI_T_BIND_MPI_SESSION = 0;
int UNIMPI_T_BIND_INVALID = 0;

/* UNIMPI_T_SCOPE_* */
int UNIMPI_T_SCOPE_CONSTANT = 0;
int UNIMPI_T_SCOPE_READONLY = 0;
int UNIMPI_T_SCOPE_LOCAL = 0;
int UNIMPI_T_SCOPE_GROUP = 0;
int UNIMPI_T_SCOPE_GROUP_EQ = 0;
int UNIMPI_T_SCOPE_ALL = 0;
int UNIMPI_T_SCOPE_ALL_EQ = 0;
int UNIMPI_T_SCOPE_INVALID = 0;

/* UNIMPI_T_SOURCE_* */
int UNIMPI_T_SOURCE_ORDINARY = 0;
int UNIMPI_T_SOURCE_DISTRIBUTED = 0;

/* UNIMPI_T_VERBOSITY_* */
int UNIMPI_T_VERBOSITY_USER_BASIC = 0;
int UNIMPI_T_VERBOSITY_USER_DETAIL = 0;
int UNIMPI_T_VERBOSITY_USER_ALL = 0;
int UNIMPI_T_VERBOSITY_TUNER_BASIC = 0;
int UNIMPI_T_VERBOSITY_TUNER_DETAIL = 0;
int UNIMPI_T_VERBOSITY_TUNER_ALL = 0;
int UNIMPI_T_VERBOSITY_MPIDEV_BASIC = 0;
int UNIMPI_T_VERBOSITY_MPIDEV_DETAIL = 0;
int UNIMPI_T_VERBOSITY_MPIDEV_ALL = 0;
int UNIMPI_T_VERBOSITY_INVALID = 0;

/* UNIMPI_T_*_NULL handles */
intptr_t UNIMPI_T_PVAR_HANDLE_NULL = 0;
intptr_t UNIMPI_T_CVAR_HANDLE_NULL = 0;
intptr_t UNIMPI_T_PVAR_SESSION_NULL = 0;
#endif /* UNIMPI_MPI_AT_LEAST(3,0) */
